# Generated by Django 4.2.7 on 2025-04-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_alter_documenthistory_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="icon",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
