# Generated by Django 5.1.7 on 2025-04-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_document_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenthistory",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("edit", "Редактирование"),
                    ("create", "Создание"),
                    ("view", "Просмотр"),
                    ("share", "Предоставление доступа"),
                    ("revoke", "Отзыв доступа"),
                    ("title_change", "Изменение заголовка"),
                    ("nested_create", "Создание вложенного документа"),
                    ("task_complete", "Завершение задачи"),
                    ("update_access", "Изменение роли"),
                ],
                default="edit",
                max_length=20,
            ),
        ),
    ]
